spring:
  application:
    name: back
  datasource:
    url: jdbc:h2:./db_dev;Mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  output:
#    ansi:
#      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE